import { Team } from '@/types/pokemon';

export const sampleTeam: Team = {
  id: 'sample-team-1',
  name: 'サンプルパーティ',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  pokemon: [
    {
      id: 'sample-1',
      speciesId: 547,
      species: 'エルフーン',
      level: 50,
      gender: 'メス',
      ability: 'いたずらごころ',
      item: 'きあいのタスキ',
      nature: 'おくびょう',
      moves: ['ふくろだたき', 'おいかぜ', 'ちょうはつ', 'くさぶえ'],
    },
    {
      id: 'sample-2',
      speciesId: 639,
      species: 'テラキオン',
      level: 50,
      ability: 'せいぎのこころ',
      item: 'ヨプのみ',
      nature: 'ようき',
      moves: ['インファイト', 'いわなだれ', 'ファストガード', 'まもる'],
    },
    {
      id: 'sample-3',
      speciesId: 235,
      species: 'ドーブル',
      level: 50,
      gender: 'オス',
      ability: 'マイペース',
      item: 'こだわりスカーフ',
      moves: ['ダークホール', 'ねこだまし', 'ファストガード', 'へんしん'],
    },
    {
      id: 'sample-4',
      speciesId: 6,
      species: 'リザードン',
      level: 50,
      gender: 'オス',
      ability: 'もうか',
      item: 'リザードナイトY',
      nature: 'ひかえめ',
      moves: ['かえんほうしゃ', 'ねっぷう', 'ソーラービーム', 'まもる'],
    },
    {
      id: 'sample-5',
      speciesId: 10021,
      species: 'ランドロス(れいじゅうフォルム)',
      level: 50,
      gender: 'オス',
      ability: 'いかく',
      item: 'とつげきチョッキ',
      nature: 'いじっぱり',
      moves: ['じしん', 'ストーンエッジ', 'ばかぢから', 'はたきおとす'],
    },
    {
      id: 'sample-6',
      speciesId: 681,
      species: 'ギルガルド',
      level: 50,
      gender: 'メス',
      ability: 'バトルスイッチ',
      item: 'いのちのたま',
      nature: 'れいせい',
      moves: ['シャドーボール', 'アイアンヘッド', 'ワイドガード', 'キングシールド'],
    },
  ],
};
